### ISSUE TITLE
Jerky motion

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#1]
https://github.com/marekmaskarinec/vaultjam2/blob/edb61d760378b30be3f8920ecc9364fa45b67e5a/gamescn.um#L133

Rounding the player position increments makes the motion jerky, so it's almost impossible to play on my machine. When I set `magespeed = 0.2`, the motion is smooth but too fast.

I think the right way is to always increment a _floating-point_ position and then round it to the nearest integer:
```
mage.p.realx += magespeed * tophat.delta * mx
mage.p.x = round(mage.p.realx)
```
The problem is that you'll have to "synchronize" `realx` with `x` each time you modify one of them.

**Comment by marekmaskarinec** [comment]
Yes. I know about this issue. I already added this to tophat's todo a while back. That will be a huge improvement, since it will also allow for more precise collisions.

On the other hand it is weird, that this is happening to you, since it works ok for me. Could you please tell me, how many fps/how big delta is? This shouldn't be a problem on lower fps (and idk, how it could get to less than 60, since it runs ok even on my chromebook) and the game is capped on 60 fps, so high framerates shouldn't be a problem. Could you also please report your resolution?

**Comment by vtereshkov** [comment]
When I compute the frame rate myself, by averaging over 500 frames, I get about 300...400 FPS. Your `tophat.delta` is usually 2, 3 or 4, sometimes 5. So calculating `round(0.1 * tophat.delta)` gives zero and the player is stuck most of the time. I'm running the game on an old 1.6 GHz laptop.

Now I think the same problem makes enemies' projectiles miss the target.

I don't have a complete solution to this problem. I just tried the two lines above (with `realx` and `realy` as globals) and saw it helped. Though I didn't synchronize them with `mage.p.x` and `mage.p.y`.

**Comment by marekmaskarinec** [comment]
> I get about 300...400 FPS

This is weird. I thought vsync was on by default (and it is on both my machines), but it seems like it isn't on everywhere. What platform did you try it on?

> Now I think the same problem makes enemies' projectiles miss the target.

Interesting. How exactly do these two relate with each other?

> I don't have a complete solution to this problem. I just tried the two lines above (with realx and realy as globals) and saw it helped. Though I didn't synchronize them with mage.p.x and mage.p.y.

I have two possible solutions. 

First is to just change stuff in umka and round it when making `cent` and `cpoly`. This will be by far the easiest one.

The second one is, that I will change stuff in c too and they I could make setting, if it should be rounded before scaling is applied or after scaling is applied. I still don't know, which one of those two to choose, but I plan on making it after I finish this with all the other stuff. Before that I will just specify to turn vsync on.

**Comment by vtereshkov** [comment]
> What platform did you try it on?

Windows 7
> Interesting. How exactly do these two relate with each other?

By these statements:
```
p.mx = speed * cos(rot * std.pi / 180)
p.ent.p.x += round(p.mx * tophat.delta)
```
Roughly speaking, you are rounding a cosine here. For large angles, you can easily get zero.
> First is to just change stuff in umka and round it when making cent and cpoly.

I like this approach.

**Comment by marekmaskarinec** [comment]
I'm trying to convert tophat to real now, but that will take some time, because I seem to have some crashes. I will close this now.

**Comment by marekmaskarinec** [comment]
The fix works. You can now move much slower and it still won't stop you completely.

The crash happens in `generator.um` on line 50, when it checks for collisions. Polygon's verticies seem to be null for some reason.

**Comment by vtereshkov** [comment]
This is because you first initialize the array with null pointers and then _append_ non-null pointers, so that the first items are still null:
```
		scn := make([]^entity.ent, len(s.trees))
		for j:=0; j < len(s.trees); j++ {
			scn = append(scn, &s.trees[j])
		}
```

**Comment by marekmaskarinec** [comment]
Oh. I see. I forgot I used make.

**Comment by vtereshkov** [comment]
Hmm, you still have the problem with projectiles:
```
	p.ent.p.x += round(p.mx * tophat.delta)
	p.ent.p.y += round(p.my * tophat.delta)
```
