### ISSUE TITLE
Segmentation fault on exit

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#10]
Probably in `free(sounds);` in `audio.c`

**Comment by marekmaskarinec** [comment]
Yes this seems to be an issue (although more of a tophat one). I probably shouldn't free the sound array in c, since it comes from umka.

**Comment by vtereshkov** [comment]
This is an interesting point. If it is a global array in Umka. it should be deallocated on returning from `main()`. But if I close the window, do I return from `main()`?

**Comment by vtereshkov** [comment]
Anyway, it is safer not to delete the array at all than to delete it twice.

**Comment by marekmaskarinec** [comment]
> But if I close the window, do I return from main()?

No. I don't think you do. I could make some kind of shouldclose variable, but I don't know, how exactly CNFGHandleDestroy works. Is there a way to quit umka from c?

**Comment by vtereshkov** [comment]
I think you can declare a global pointer:
```
var shouldclose: ^int
```
bind it to a C variable:
```
fn bindshouldclose(p: ^int) {    // Call it from C and pass the pointer to a C global variable
    shouldclose = p
}
```
and check it in the game loop in `main()`:
```
if shouldclose^ != 0 {
    break
}

**Comment by marekmaskarinec** [comment]
I thought about this, but what if the program closes before the loop ends. I have the `handledestroy` method, where you can free your own stuff.

**Comment by vtereshkov** [comment]
For now, let's comment out `free(sounds);`. After the jam we can discuss it again. Currently I don't even understand what happens with `main()` in C on exit.

**Comment by marekmaskarinec** [comment]
I commented out `free(sounds);` and put `umkaFree` to `HandleDestroy`.

**Comment by vtereshkov** [comment]
It became even worse after moving `umkaFree()`. Just commenting out `free(sounds);` gives better behavior.
