### ISSUE TITLE
Bullet texture not used in tutorial

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#11]
![image](https://user-images.githubusercontent.com/52492460/113927539-4af12a00-97f6-11eb-9406-6275d9c1364d.png)

**Comment by marekmaskarinec** [comment]
Fixed https://github.com/marekmaskarinec/vaultjam2/commit/410e9ab73f99feaf6768f89e143cc2cadcdcf44e
