### ISSUE TITLE
Segmentation fault on completing the tutorial

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#12]
![image](https://user-images.githubusercontent.com/52492460/114001618-c5589300-9864-11eb-8c79-d83c28ccd9a8.png)

**Comment by vtereshkov** [comment]
The problem is with `prjimg.delete()`.

**Comment by marekmaskarinec** [comment]
Interesting. That seems to be a problem with the delete method itself. I will look into it.

**Comment by vtereshkov** [comment]
I have found at least two places which look highly suspicious to me:
* You call `stbi_image_free(img->raw);` in both `umimgload()` and `umimgfree()`
* You call `tutorial.init()` only once while `prjimg.delete()` is called on every exit from the tutorial screen.

**Comment by marekmaskarinec** [comment]
This should be fixed now. Does it work?

**Comment by vtereshkov** [comment]
Nice! Closing
