### ISSUE TITLE
Different tophat behavior

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#13]
With `RAIDER.exe`, I again have segmentation faults on exit. With `tophat.exe` built from your source (`mingw32-make windows`), no issues are seen.

Moreover, these two versions render fonts differently.

**Comment by marekmaskarinec** [comment]
Yes. I changed the font writing. I forgot to install new windows version. I will fix it right away.

**Comment by marekmaskarinec** [comment]
I updated the release. Try it now.

**Comment by vtereshkov** [comment]
OK!
