### ISSUE TITLE
Dangerous use of delete()

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#2]
https://github.com/marekmaskarinec/vaultjam2/blob/74140e4a639231cb4b0df275aaf8cfeee2bba6d4/gamescn.um#L135

Deleting array items while iterating through the same array may lead to unpredictable results. AFAIK, this is also true in Go.

**Comment by marekmaskarinec** [comment]
Fixed [here](https://github.com/marekmaskarinec/vaultjam2/commit/fbe59be7aa55e3fb21bdcda2976e84a6e2460c01)
