### ISSUE TITLE
Enemy is not shooting and cannot be killed

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#3]
![image](https://user-images.githubusercontent.com/52492460/113405989-5fc35d00-93b3-11eb-862d-55d5c2730156.png)

**Comment by marekmaskarinec** [comment]
Interesting. Is this happening with all enemies in all villages, or is it just this one?

**Comment by vtereshkov** [comment]
One enemy per several villages, on average.

**Comment by marekmaskarinec** [comment]
Ok. I have several questions. Do you have the latest version? Is the fire always visible? Does this happen only, when coordinates are negative? Could you please print lenght of the enemy array?

**Comment by vtereshkov** [comment]
This was the previous version with the fire always visible. I cannot reproduce exactly this problem with the latest version. But now I see a (similar?) issue, which often happens when the player is to the right from the enemies. It seems that the projectiles of both the player and the enemy have limited range and cannot reach their targets.

![image](https://user-images.githubusercontent.com/52492460/113408659-66a09e80-93b8-11eb-958c-a9bf1bc50b17.png)

**Comment by marekmaskarinec** [comment]
That is weird. The projectile should get deleted, when it is on the borders of a screen. I think, I've seen this issuse yesterday and fixed it by changing the values a bit. I have no idea, why this is happening. I will try running it on windows to see, if something changes.

**Comment by marekmaskarinec** [comment]
I was able to recreate this issue on windows. I also found out, it doesn't have anything to do with bullet deleting. I will look into it later.

**Comment by marekmaskarinec** [comment]
Oh. There is problem with the deletion.

**Comment by marekmaskarinec** [comment]
@vtereshkov I think, I fixed it. Could you please try it now?

**Comment by vtereshkov** [comment]
Yes, the bullets no longer "disappear", so the second problem is gone. But the first problem (enemies who cannot shoot and cannot be shot) is still there. I'll try to print some debug info if it happens again.

**Comment by marekmaskarinec** [comment]
They way I did it stopped bullets from dissapearing, but they would never despawn. I pushed a fix for that now.

I recommend printing the seed in generator and then if you find a faulty village, you can easily get back to it by hard coding the seed you got before. It can really help with debugging.

**Comment by vtereshkov** [comment]
It looks like every village located upwards from the player's initial screen is faulty. This does not depend on the village seed number. If I fix the seed, I get normal villages in front of me and faulty villages upwards.

**Comment by marekmaskarinec** [comment]
I think I just fixed this a minute ago. Could you test it now?

**Comment by vtereshkov** [comment]
Seems to be OK.
