### ISSUE TITLE
Convenient controls

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#5]
It seems to me inconvenient to have E as the firing key. I think the left hand should be used for movement control, the right hand (Enter or Spacebar) for firing. Otherwise I cannot move and shoot simultaneously.

**Comment by marekmaskarinec** [comment]
I completely agree. I will be adding two new types of attack, so I will probably rebind the keys a bit.

**Comment by marekmaskarinec** [comment]
I rebinded shooting to enter, added slide to space and shield to e. Could I get your thoughts on this?

**Comment by vtereshkov** [comment]
Much better! As for the shield, I don't know exactly its use cases, so I cannot say whether E is a suitable choice or not.
