### ISSUE TITLE
Hanging on startup

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#6]
Sometimes (1 per 10 runs on average) the game gets stuck in the infinite loop in `player.um` without showing anything on the screen:
```
		for coll > 0 {
			mage.p.x -= mx
			coll = mage.getcoll(scn)
		}
```

**Comment by marekmaskarinec** [comment]
That is already on todo. I think it can be fixed by setting player's position to 96, 54, where trees don't spawn.

**Comment by marekmaskarinec** [comment]
I solved this a while back.
