### ISSUE TITLE
Everything is too fast

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#7]
After pulling your latest commits, I see that everything is now happening several times faster than before: motion, shooting. animations etc. The player's head is shaking as if he suffers from Parkinson's disease.

**Comment by marekmaskarinec** [comment]
Interesting. I wasn't able to recreate this issue. Could you try updating tophat, since I made some changes there? Please also print your delta.

**Comment by vtereshkov** [comment]
The `delta` looks like 10, 0, 0, 0, 10, 0, 0, 0, 10... It may be a problem with the timer discreteness on Windows. If I replace 0 with 1 rather than 17, everything looks fine.

**Comment by marekmaskarinec** [comment]
Try it now.

**Comment by vtereshkov** [comment]
Good!
