### ISSUE TITLE
Tutorial problems

### ISSUE THREAD

**Issue by vtereshkov** [marekmaskarinec/vaultjam2#9]
1. Cannot run the tutorial after finishing a normal game.
2. Text lines are too long.

![image](https://user-images.githubusercontent.com/52492460/113759414-b61afd80-971d-11eb-9d47-4c59846f5b94.png)

**Comment by marekmaskarinec** [comment]
Yes, this seems to be an issue. The drawtext function from rawdraw gets size as short, so scaling isn't done correctly. I will make the text smaller for now, since I definitely won't be able to implement truetype support.

**Comment by marekmaskarinec** [comment]
Fixed in https://github.com/marekmaskarinec/vaultjam2/commit/029e4502fc3fa2de12bcc3efd4f3300875c35ccd

**Comment by vtereshkov** [comment]
Yes, nice. But the first problem is still there.

**Comment by marekmaskarinec** [comment]
Interesting. I'm not able to recreate it.

**Comment by vtereshkov** [comment]
OK. I will try to find out where it happens

**Comment by marekmaskarinec** [comment]
Oh. You meant the first one. I kinda missed it. I will look into it.

**Comment by vtereshkov** [comment]
Yes. The problem is in `player.um`:
```
	if hp <= 0 {
		global.scene = global.MENU
		// ...
		}
	}
```
I think that `hp` is not reset after finishing a normal game and is still zero.

**Comment by marekmaskarinec** [comment]
I pushed a new commit, that should fix it.

**Comment by vtereshkov** [comment]
OK. Closing.

P. S. I would write `w/a/s/d + SPACE` for dashing rather than just `SPACE`. When I press space bar, nothing happens.

**Comment by marekmaskarinec** [comment]
I don't think, that is a problem with the tutorial as much as a problem with dash itself. I should probably use data from rotation, if mx an my are both zero.
